plugins {
    id 'base'
    id 'net.minecraftforge.gradle' version '6.0.54' apply false
}

allprojects {
    group = 'io.github.whiteviera.trashbin'
    version = rootProject.mod_version
    repositories { mavenCentral() }
}

subprojects {
    if (name.startsWith('forge-')) {
        apply from: rootProject.file('gradle/forge.gradle')
    }
}

tasks.named('build') { dependsOn subprojects.collect { it.tasks.named('build') } }
tasks.register('release', Copy) {
    dependsOn tasks.named('build')
    from(subprojects.findAll { it.name.startsWith('forge-') }.collect {
        it.layout.buildDirectory.dir('libs')
    }) { include '*.jar'; exclude '*-sources.jar' }
    into layout.projectDirectory.dir('dist')
}
