modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All Rights Reserved"

[[mods]]
modId="trashbin"
version="${mod_version}"
displayName="Trash Bin"
authors="whiteviera"
description='''
A compact, resource-pack-friendly trash bin with 27 slots, experience recycling,
FIFO automation, fluid disposal and optional liquid experience output.
'''

[[dependencies.trashbin]]
modId="forge"
mandatory=true
versionRange="[${loader_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.trashbin]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
